name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - matplotlib
  - pandas
  - ipycanvas
  - jinja2
  - tabulate
  - BeautifulSoup4
  - html5lib
  - lxml
  - jupytext
  - ipyevents
  - ipympl
  - ipywidgets
  - ipydatagrid #just use via pip?
  - jupyterlab-filesystem-access
  - ipyaggrid

