name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - matplotlib
  - pandas
  - scipy
  - python-dateutil
  - pytz
  - tzdata
  - jinja2
  - tabulate
  - BeautifulSoup4
  - html5lib
  - lxml
  - jupytext
  - ipyevents
  - ipympl
  - ipywidgets
  
